# -*- coding: utf-8 -*-
"""notebook60d40ab84e

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/scratchpad/notebook60d40ab84e.f8e39236-2667-4d08-bb02-0f7eae93c26e.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250430/auto/storage/goog4_request%26X-Goog-Date%3D20250430T101803Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3Da3326e510708d25827a77a29c01fb0e6271dc6ddcb26639153220ec9eeaa5c4a720eb4562a8c818a936c298c60ada107961239a9a7a846c5565b5d80dcf1f8b53196d09cfde3f5969b4d245a0e43078b50de4feb460f22272ca65826bd0a97a6edfd0ae45fc47775cfeb4bd8c47ab3a46a9f61761f030db439c3f28c3233c2d8f2d9038e2086bc27dd676710bb16ab843b2ef13cc26927336356d1f289f45f4e814b8c9470504ced114010429758f629eea168061dc9f4521a626c6edc492440f0b9a98b0603f68be888ce84f93fa54cc8628a7683f2c157c4dc4d503744870b52334977f45dff9b1cf92f43bf24c0e479df03bdb71d6a0bbd1e8d00b5c0eb4f
"""

import kagglehub
harishkumardatalab_housing_price_prediction_path = kagglehub.dataset_download('harishkumardatalab/housing-price-prediction')

print('Data source import complete.')

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

import warnings
warnings.filterwarnings("ignore")

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import seaborn as sns

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# Step 1: Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.preprocessing import StandardScaler

# Step 2: Load the Dataset
df = pd.read_csv('/kaggle/input/housing-price-prediction/Housing.csv')

# Display the first few rows of the dataset
print(df.head())
print(df.shape)

# Missing Data
missing_data = df.isnull().sum()
print(missing_data[missing_data > 0])

# Outliers
import seaborn as sns
import matplotlib.pyplot as plt

sns.boxplot(data=df['price'])
plt.show()

sns.boxplot(data=df['area'])
plt.show()

# Histogram
sns.histplot(df['price'], kde=True)
plt.show()

sns.histplot(df['area'], kde=True)
plt.show()

# Scatterplot
sns.pairplot(df)
plt.show()

from sklearn.model_selection import train_test_split

random_seed = 42

def train_test_split_equal(df, test_size=0.2):
    df = df.sample(frac=1, random_state=random_seed).reset_index(drop=True)
    train_df, test_df = train_test_split(df, test_size=test_size, random_state=random_seed)
    return train_df, test_df

train_df, test_df = train_test_split_equal(df)

print("Training set size:", len(train_df))
print("Test set size:", len(test_df))

# Preprocessing - Handling Missing Values (if any)
# Example: Fill missing values with median for numerical columns (modify as needed)
for column in train_df.columns:
    if train_df[column].isnull().any():
        if train_df[column].dtype == 'object':
            train_df[column].fillna(train_df[column].mode()[0], inplace=True)
        else:
            train_df[column].fillna(train_df[column].median(), inplace=True)

# Feature Engineering - Convert categorical variables to numerical
train_df = pd.get_dummies(train_df, drop_first=True)
test_df = pd.get_dummies(test_df, drop_first=True)

# Align the columns of train and test sets to ensure they match after one-hot encoding
train_df, test_df = train_df.align(test_df, join='left', axis=1, fill_value=0)

# Scaling features
scaler = StandardScaler()
X_train = scaler.fit_transform(train_df.drop('price', axis=1))
y_train = train_df['price']
X_test = scaler.transform(test_df.drop('price', axis=1))
y_test = test_df['price']

# Modeling - Implementing Algorithms

# 1. Linear Regression
linear_model = LinearRegression()
linear_model.fit(X_train, y_train)
linear_pred = linear_model.predict(X_test)

# 2. Decision Tree Regressor
tree_model = DecisionTreeRegressor(random_state=random_seed)
tree_model.fit(X_train, y_train)
tree_pred = tree_model.predict(X_test)

# 3. Random Forest Regressor
forest_model = RandomForestRegressor(random_state=random_seed)
forest_model.fit(X_train, y_train)
forest_pred = forest_model.predict(X_test)

# 4. XGBoost Regressor
xgb_model = XGBRegressor(random_state=random_seed)
xgb_model.fit(X_train, y_train)
xgb_pred = xgb_model.predict(X_test)

# Evaluation Metrics Function
def evaluate_model(y_true, y_pred):
    rmse = mean_squared_error(y_true, y_pred, squared=False)
    mae = mean_absolute_error(y_true, y_pred)
    return rmse, mae

# Evaluate models
models_performance = {
    'Linear Regression': evaluate_model(y_test, linear_pred),
    'Decision Tree': evaluate_model(y_test, tree_pred),
    'Random Forest': evaluate_model(y_test, forest_pred),
    'XGBoost': evaluate_model(y_test, xgb_pred),
}

# Display results in a score table format
score_table = pd.DataFrame(models_performance).T
score_table.columns = ['RMSE', 'MAE']
print(score_table)

# Regularization - Lasso and Ridge Regression

# Lasso Regression
lasso_model = Lasso(random_state=random_seed)
lasso_model.fit(X_train, y_train)
lasso_pred = lasso_model.predict(X_test)

# Ridge Regression
ridge_model = Ridge(random_state=random_seed)
ridge_model.fit(X_train, y_train)
ridge_pred = ridge_model.predict(X_test)

# Evaluate regularized models
regularized_performance = {
    'Lasso Regression': evaluate_model(y_test, lasso_pred),
    'Ridge Regression': evaluate_model(y_test, ridge_pred),
}

regularized_score_table = pd.DataFrame(regularized_performance).T
regularized_score_table.columns = ['RMSE', 'MAE']
print(regularized_score_table)

# Display the score table
print("Model Performance Summary:")
print(score_table)

# Identify the best model based on RMSE
best_rmse_model = score_table['RMSE'].idxmin()
best_rmse_value = score_table['RMSE'].min()

# Identify the best model based on MAE
best_mae_model = score_table['MAE'].idxmin()
best_mae_value = score_table['MAE'].min()

# Print results
print("\nBest Model Based on RMSE:")
print(f"Model: {best_rmse_model}, RMSE: {best_rmse_value}")

print("\nBest Model Based on MAE:")
print(f"Model: {best_mae_model}, MAE: {best_mae_value}")

